// Generated by Haxe 4.3.1
/* eslint-disable */
;import { Component as react_ReactComponentOf } from "react";
import react_React from "react";
import react_ReactDOM from "react-dom";
import react_ReactDOMClient from "react-dom/client";
import react_ReactHooks from "react";
;var $global = typeof window != "undefined" ? window : typeof global != "undefined" ? global : typeof self != "undefined" ? self : this;
class App extends react_ReactComponentOf {
	constructor() {
		super();
		App.email = "";
		this.state = { showThankState : false};
	}
	set_showThankState(value) {
		this.setState(function(previousState) {
			return { showThankState : value};
		});
		return this.showThankState = value;
	}
	render() {
		if(!this.state.showThankState) {
			return { $$typeof : $$tre, type : "div", props : { children : [{ $$typeof : $$tre, type : "div", props : { className : "newsletter", children : { $$typeof : $$tre, type : App_Signup, props : { parent : this}, key : null, ref : null}}, key : null, ref : null},{ $$typeof : $$tre, type : "div", props : { className : "credits", children : ["Challenge by ",{ $$typeof : $$tre, type : "a", props : { target : "_blank", href : "https://www.frontendmentor.io?ref=challenge", className : "underline", children : "Frontend Mentor"}, key : null, ref : null},". Coded by ",{ $$typeof : $$tre, type : "a", props : { target : "_blank", href : "https://github.com/Just-Feeshy", className : "underline", children : "Diego Fonseca"}, key : null, ref : null},"."]}, key : null, ref : null}]}, key : null, ref : null};
		} else {
			let tmp = $$tre;
			let tmp1 = { $$typeof : $$tre, type : "div", props : { className : "newsletter", children : { $$typeof : $$tre, type : App_Thank, props : { parent : this}, key : null, ref : null}}, key : null, ref : null};
			let tmp2 = $$tre;
			let tmp3 = $$tre;
			let tmp4 = $$tre;
			return { $$typeof : tmp, type : "div", props : { children : [tmp1,{ $$typeof : tmp2, type : "div", props : { className : "credits", children : { $$typeof : tmp3, type : "div", props : { style : { display : "flex", justifyContent : "center", alignItems : "center"}, className : "promo", children : ["Mainly programmed with Haxe",{ $$typeof : tmp4, type : "img", props : { style : { display : "block", width : "40px"}, src : "haxe-logo.svg", className : "haxe-image", alt : "logo"}, key : null, ref : null}]}, key : null, ref : null}}, key : null, ref : null}]}, key : null, ref : null};
		}
	}
}
function App_isValidEmail(email) {
	return new EReg("^[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}$","").match(email);
}
function App_checkElement(item) {
	return { $$typeof : $$tre, type : "div", props : { className : "checkelement", children : [{ $$typeof : $$tre, type : "img", props : { width : "50", src : "/icon-list.svg", height : "50"}, key : null, ref : null},{ $$typeof : $$tre, type : "p", props : { children : item}, key : null, ref : null}]}, key : null, ref : null};
}
function App_subscribe(emailInput,parent,hook) {
	if(emailInput.current == null) {
		return;
	}
	let isValid = App_isValidEmail(emailInput.current.value);
	react_HookState.set_value(hook,!isValid);
	if(!react_HookState.get_value(hook)) {
		parent.set_showThankState(true);
		App.email = emailInput.current.value;
	}
}
function App_Signup(props) {
	let activeError = react_ReactHooks.useState(false);
	let emailInput = react_ReactHooks.useRef(null);
	let items = ["Product discovery and building what matters","Measuring to ensure updates are a success","And much more!"];
	let f = App_checkElement;
	let result = new Array(items.length);
	let _g = 0;
	let _g1 = items.length;
	while(_g < _g1) {
		let i = _g++;
		result[i] = f(items[i]);
	}
	let setRef = function(ref) {
		emailInput.current = ref;
	};
	let tmp = $$tre;
	let tmp1 = $$tre;
	let tmp2 = { $$typeof : $$tre, type : "h1", props : { children : "Stay updated!"}, key : null, ref : null};
	let tmp3 = { $$typeof : $$tre, type : "p", props : { children : "Join 60,000+ product managers recieving receiving monthly updates on:"}, key : null, ref : null};
	let tmp4 = { $$typeof : $$tre, type : "div", props : { className : "checklist", children : result}, key : null, ref : null};
	let tmp5 = $$tre;
	let tmp6 = $$tre;
	let tmp7 = { $$typeof : $$tre, type : "div", props : { className : "email", children : "Email address"}, key : null, ref : null};
	let tmp8 = $$tre;
	let tmp9 = react_HookState.get_value(activeError) ? "Valid email required" : "";
	let tmp10 = { $$typeof : $$tre, type : "input", props : { type : "email", style : { borderColor : react_HookState.get_value(activeError) ? "hsl(4, 100%, 67%)" : "", color : react_HookState.get_value(activeError) ? "hsl(4, 100%, 67%)" : ""}, placeholder : "email@company.com"}, key : null, ref : setRef};
	let tmp11 = $$tre;
	return { $$typeof : tmp, type : "div", props : { className : "signup", children : [{ $$typeof : tmp1, type : "div", props : { className : "info", children : [tmp2,tmp3,tmp4,{ $$typeof : tmp5, type : "div", props : { className : "userinputs", children : [{ $$typeof : tmp6, type : "div", props : { className : "label-box", children : [tmp7,{ $$typeof : tmp8, type : "div", props : { className : "error", children : tmp9}, key : null, ref : null}]}, key : null, ref : null},tmp10,{ $$typeof : tmp11, type : "button", props : { onClick : function(e) {
		App_subscribe(emailInput,props.parent,activeError);
	}, children : "Subscribe to monthly newsletter"}, key : null, ref : null}]}, key : null, ref : null}]}, key : null, ref : null},{ $$typeof : $$tre, type : "div", props : { className : "right", children : { $$typeof : $$tre, type : "img", props : { src : "/illustration-sign-up-desktop.svg", height : "600px"}, key : null, ref : null}}, key : null, ref : null}]}, key : null, ref : null};
}
function App_dismiss(parent) {
	parent.set_showThankState(false);
}
function App_Thank(props) {
	return { $$typeof : $$tre, type : "div", props : { className : "thanks", children : [{ $$typeof : $$tre, type : "div", props : { children : [{ $$typeof : $$tre, type : "div", props : { children : { $$typeof : $$tre, type : "img", props : { src : "/icon-success.svg"}, key : null, ref : null}}, key : null, ref : null},{ $$typeof : $$tre, type : "h1", props : { children : "Thanks for subscribing!"}, key : null, ref : null},{ $$typeof : $$tre, type : "p", props : { children : ["A confirmation email has been sent to ",{ $$typeof : $$tre, type : "span", props : { children : App.email}, key : null, ref : null},". Please open it and click the button inside to confirm your subscription."]}, key : null, ref : null}]}, key : null, ref : null},{ $$typeof : $$tre, type : "button", props : { onClick : function(e) {
		App_dismiss(props.parent);
	}, children : "Dismiss message"}, key : null, ref : null}]}, key : null, ref : null};
}
class EReg {
	constructor(r,opt) {
		this.r = new RegExp(r,opt.split("u").join(""));
	}
	match(s) {
		if(this.r.global) {
			this.r.lastIndex = 0;
		}
		this.r.m = this.r.exec(s);
		this.r.s = s;
		return this.r.m != null;
	}
}
function Main_main() {
	let root = react_ReactDOMClient.createRoot(window.document.getElementById("root"));
	let tmp = $$tre;
	let tmp1 = react_React.StrictMode;
	let tmp2 = $$tre;
	root.render({ $$typeof : tmp, type : tmp1, props : { children : { $$typeof : tmp2, type : App, props : { }, key : null, ref : null}}, key : null, ref : null});
}
class haxe_iterators_ArrayIterator {
	constructor(array) {
		this.current = 0;
		this.array = array;
	}
	hasNext() {
		return this.current < this.array.length;
	}
	next() {
		return this.array[this.current++];
	}
}
class react_HookState {
	static get_value(this1) {
		return this1[0];
	}
	static set_value(this1,param) {
		this1[0] = param;
		this1[1](param);
		return param;
	}
}
var $$tre = (typeof Symbol === "function" && Symbol.for && Symbol.for("react.element")) || 0xeac7;
{
}
App.displayName = "App";
Main_main();
